[book]
title = "Rust API Guidelines（Rust API 准则）"
description = "关于如何设计和呈现 Rust APIs 的一些建议"
language = "zh"

[output.html]
git-repository-url = "https://github.com/zjp-CN/api-guidelines"
additional-css = ["theme/style.css"]
additional-js = ["theme/sidebar.js"]

[output.html.fold]
enable = true
level = 0

[output.html.playground]
editable = false

[output.html.print]
enable = false
