[book]
title = "Rust API Guidelines（Rust API 编写指南）"
description = "关于如何设计和呈现 Rust APIs 的一些建议"
language = "zh"

[preprocessor.theme]
pagetoc = true
turn-off = true
root-font-size = "70%"
sidebar-width = "120px"
pagetoc-width = "15%"
content-max-width = "80%"

[output.html]
git-repository-url = "https://github.com/zjp-CN/api-guidelines"
additional-css = ["theme/pagetoc.css"] 
additional-js = ["theme/pagetoc.js"] 

[output.html.fold]
enable = true
level = 0

[output.html.playground]
editable = true

[output.html.print]
enable = false

[output.theme-ace]
theme-white = "github"
theme-dark = "solarized_dark"
below-build-dir = true 
